SELECT 
-- BUSSINESS_ENTITY_EVENT_ID
-- BUSSINESS_ENTITY_ID
   DATE_TRUNC('week',DATE_1) AS DATE_1_WEEK_LEVEL
-- DATE_2
,  DIM_1
-- DIM_N
,  KPI_1_Discrete_NUMERIC_VALUE

,  AVG(KPI_2_Continuous_NUMERIC_VALUE) AS AVG_KPI_2
,  MEDIAN(KPI_2_Continuous_NUMERIC_VALUE) AS MEDIAN_KPI_2
,  PERCENTILE_CONT(0.95)  WITHIN GROUP (ORDER BY  KPI_2_Continuous_NUMERIC_VALUE) AS P95_KPI_2

,  AVG(DATEDIFF('day',DATE_1,DATE_2)) AS AVG_DATE1_TO_DATE2
,  COUNT(BUSSINESS_ENTITY_EVENT_ID) AS EVENTS_COUNT


,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 1 THEN 1 ELSE 0 END ) AS BUCKET_1_KPI_1_RT -- running total
,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 2 THEN 1 ELSE 0 END) AS BUCKET_2_KPI_1_RT -- running total
,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 3 THEN 1 ELSE 0 END) AS BUCKET_3_KPI_1_RT -- running total
,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 4 THEN 1 ELSE 0 END) AS BUCKET_4_KPI_1_RT -- running total
,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 5 THEN 1 ELSE 0 END) AS BUCKET_5_KPI_1_RT -- running total
,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 6 THEN 1 ELSE 0 END) AS BUCKET_6_KPI_1_RT -- running total
,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 7 THEN 1 ELSE 0 END) AS BUCKET_7_KPI_1_RT -- running total
,  SUM(CASE WHEN KPI_1_Discrete_NUMERIC_VALUE<= 8 THEN 1 ELSE 0 END) AS BUCKET_8_KPI_1_RT -- running total

,  COUNT(KPI_1_Discrete_NUMERIC_VALUE) AS  COUNT_KPI_1
,  SUM(KPI_1_Discrete_NUMERIC_VALUE) AS SUM_KPI_1

FROM CS_DB.CS_STAGE.SAMPLE_MEDIANS
GROUP BY DATE_TRUNC('week',DATE_1),DIM_1,KPI_1_Discrete_NUMERIC_VALUE
