SELECT 
-- BUSSINESS_ENTITY_EVENT_ID
-- BUSSINESS_ENTITY_ID
   DATE_TRUNC('week',DATE_1) AS DATE_1_WEEK_LEVEL
-- DATE_2
,  DIM_1
-- DIM_N
,  KPI_1_Discrete_NUMERIC_VALUE
,  AVG(KPI_1_Discrete_NUMERIC_VALUE) AS AVG_KPI_1
,  MEDIAN(KPI_1_Discrete_NUMERIC_VALUE) AS MEDIAN_KPI_1
,  PERCENTILE_CONT(0.95)  WITHIN GROUP (ORDER BY  KPI_1_Discrete_NUMERIC_VALUE) AS P95_KPI_1
,  AVG(KPI_2_Continuous_NUMERIC_VALUE) AS AVG_KPI_2
,  MEDIAN(KPI_2_Continuous_NUMERIC_VALUE) AS MEDIAN_KPI_2
,  PERCENTILE_CONT(0.95)  WITHIN GROUP (ORDER BY  KPI_2_Continuous_NUMERIC_VALUE) AS P95_KPI_2
,  AVG(DATEDIFF('day',DATE_1,DATE_2)) AS AVG_DATE1_TO_DATE2
,  COUNT(BUSSINESS_ENTITY_EVENT_ID) AS EVENTS_COUNT
FROM SAMPLE_MEDIANS
GROUP BY DATE_TRUNC('week',DATE_1),DIM_1,KPI_1_Discrete_NUMERIC_VALUE
