CREATE OR REPLACE TRANSIENT TABLE SAMPLE_MEDIANS_BANDS 
AS
--select * from SAMPLE_MEDIANS_BANDS;

with all_data as
(
  SELECT 
-- BUSSINESS_ENTITY_EVENT_ID
-- BUSSINESS_ENTITY_ID
   DATE_TRUNC('week',DATE_1) AS DATE_1_WEEK_LEVEL
-- DATE_2
,  DIM_1
-- DIM_N
,  KPI_1_Discrete_NUMERIC_VALUE
,  KPI_2_Continuous_NUMERIC_VALUE
,  DATEDIFF('day',DATE_1,DATE_2) AS DATE1_TO_DATE2
FROM CS_DB.CS_STAGE.SAMPLE_MEDIANS
)


, kpis_list
as
(
  
SELECT 
   'KPI_1_Discrete' AS KPI_NAME
  , KPI_1_Discrete_NUMERIC_VALUE::FLOAT AS KPI_VALUE
  , * FROM all_data
UNION ALL 
    SELECT 'KPI_2_Continuous' AS KPI_NAME
    , KPI_2_Continuous_NUMERIC_VALUE::FLOAT AS KPI_VALUE
    ,* FROM all_data
UNION ALL 
    SELECT 'Days from DATE_1 to DATE_2' AS KPI_NAME
  , DATE1_TO_DATE2::FLOAT AS KPI_VALUE
  , * FROM all_data

  -- and so on for each KPI
)



,bands as
(
SELECT
    
  
  
    KPI_NAME
,	MIN(KPI_VALUE) 	AS 	MIN_KPI
,	MAX(KPI_VALUE) 	AS 	MAX_KPI
  
  
  
  
  
  
  
  
,	PERCENTILE_CONT(	0.99	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS  	ALL_P99
,	PERCENTILE_CONT(	0.98	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P98
,	PERCENTILE_CONT(	0.97	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P97
,	PERCENTILE_CONT(	0.96	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P96
,	PERCENTILE_CONT(	0.95	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P95
,	PERCENTILE_CONT(	0.9	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P90
,	PERCENTILE_CONT(	0.85	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P85
,	PERCENTILE_CONT(	0.8	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P80
,	PERCENTILE_CONT(	0.75	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P75
,	PERCENTILE_CONT(	0.7	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P70
,	PERCENTILE_CONT(	0.65	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P65
,	PERCENTILE_CONT(	0.6	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P60
,	PERCENTILE_CONT(	0.55	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P55
,	PERCENTILE_CONT(	0.5	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P50
,	PERCENTILE_CONT(	0.45	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P45
,	PERCENTILE_CONT(	0.4	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P40
,	PERCENTILE_CONT(	0.35	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P35
,	PERCENTILE_CONT(	0.3	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P30
,	PERCENTILE_CONT(	0.25	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P25
,	PERCENTILE_CONT(	0.2	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P20
,	PERCENTILE_CONT(	0.15	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P15
,	PERCENTILE_CONT(	0.1	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P10
,	PERCENTILE_CONT(	0.05	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P5
,	PERCENTILE_CONT(	0.04	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P4
,	PERCENTILE_CONT(	0.03	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P3
,	PERCENTILE_CONT(	0.02	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P2
,	PERCENTILE_CONT(	0.01	) WITHIN GROUP (ORDER BY 	KPI_VALUE	)  	AS 	ALL_P1



 FROM kpis_list
 GROUP BY 1
 )
 
 SELECT * FROM bands
  
  ;
  
  
  
with all_data as
(
  SELECT 
-- BUSSINESS_ENTITY_EVENT_ID
-- BUSSINESS_ENTITY_ID
   DATE_TRUNC('week',DATE_1) AS DATE_1_WEEK_LEVEL
-- DATE_2
,  DIM_1
-- DIM_N
,  KPI_1_Discrete_NUMERIC_VALUE
,  KPI_2_Continuous_NUMERIC_VALUE
,  DATEDIFF('day',DATE_1,DATE_2) AS DATE1_TO_DATE2
FROM CS_DB.CS_STAGE.SAMPLE_MEDIANS
)


, kpis_list
as
(
  
SELECT 
   'KPI_1_Discrete' AS KPI_NAME
  , KPI_1_Discrete_NUMERIC_VALUE::FLOAT AS KPI_VALUE
  , * FROM all_data
UNION ALL 
    SELECT 'KPI_2_Continuous' AS KPI_NAME
    , KPI_2_Continuous_NUMERIC_VALUE::FLOAT AS KPI_VALUE
    ,* FROM all_data
UNION ALL 
    SELECT 'Days from DATE_1 to DATE_2' AS KPI_NAME
  , DATE1_TO_DATE2::FLOAT AS KPI_VALUE
  , * FROM all_data

  -- and so on for each KPI
)
  
SELECT
-- bands definition
b.ALL_P99
,b.ALL_P98
,b.ALL_P97
,b.ALL_P96
,b.ALL_P95
,b.ALL_P90
,b.ALL_P85
,b.ALL_P80
,b.ALL_P75
,b.ALL_P70
,b.ALL_P65
,b.ALL_P60
,b.ALL_P55
,b.ALL_P50
,b.ALL_P45
,b.ALL_P40
,b.ALL_P35
,b.ALL_P30
,b.ALL_P25
,b.ALL_P20
,b.ALL_P15
,b.ALL_P10
,b.ALL_P5
,b.ALL_P4
,b.ALL_P3
,b.ALL_P2
,b.ALL_P1
,b.MIN_KPI
,b.MAX_KPI
,b.KPI_NAME
--
,DATE_1_WEEK_LEVEL
,DIM_1

,COUNT(KPI_VALUE) AS Population_Size
,SUM(KPI_VALUE) AS Population_Total
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P99 THEN 1 ELSE 0 END) AS P99
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P98 THEN 1 ELSE 0 END) AS P98
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P97 THEN 1 ELSE 0 END) AS P97
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P96 THEN 1 ELSE 0 END) AS P96
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P95 THEN 1 ELSE 0 END) AS P95
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P90 THEN 1 ELSE 0 END) AS P90
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P85 THEN 1 ELSE 0 END) AS P85
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P80 THEN 1 ELSE 0 END) AS P80
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P75 THEN 1 ELSE 0 END) AS P75
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P70 THEN 1 ELSE 0 END) AS P70
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P65 THEN 1 ELSE 0 END) AS P65
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P60 THEN 1 ELSE 0 END) AS P60
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P55 THEN 1 ELSE 0 END) AS P55
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P50 THEN 1 ELSE 0 END) AS P50
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P45 THEN 1 ELSE 0 END) AS P45
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P40 THEN 1 ELSE 0 END) AS P40
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P35 THEN 1 ELSE 0 END) AS P35
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P30 THEN 1 ELSE 0 END) AS P30
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P25 THEN 1 ELSE 0 END) AS P25
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P20 THEN 1 ELSE 0 END) AS P20
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P15 THEN 1 ELSE 0 END) AS P15
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P10 THEN 1 ELSE 0 END) AS P10
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P5 THEN 1 ELSE 0 END) AS P5
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P4 THEN 1 ELSE 0 END) AS P4
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P3 THEN 1 ELSE 0 END) AS P3
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P2 THEN 1 ELSE 0 END) AS P2
,SUM (CASE WHEN KPI_VALUE<= b.ALL_P1 THEN 1 ELSE 0 END) AS P1

  
FROM kpis_list kpis
LEFT JOIN SAMPLE_MEDIANS_BANDS b on b.KPI_NAME=kpis.KPI_NAME
GROUP BY  
-- bands definition
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30
-- data aggregation
,DATE_1_WEEK_LEVEL ,DIM_1
